// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPArticle;

namespace TpArticleCore.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20200114145046_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0");

            modelBuilder.Entity("TPArticle.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateSortie")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EtagereId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Poids")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixInitial")
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EtagereId");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("TPArticle.Etagere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdSecteur")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PoidsMaximum")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SecteurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SecteurId");

                    b.ToTable("Etagere");
                });

            modelBuilder.Entity("TPArticle.PositionMagasin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdArticle")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEtagere")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PositionMagasin");
                });

            modelBuilder.Entity("TPArticle.Secteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Secteur");
                });

            modelBuilder.Entity("TPArticle.Article", b =>
                {
                    b.HasOne("TPArticle.Etagere", null)
                        .WithMany("Articles")
                        .HasForeignKey("EtagereId");
                });

            modelBuilder.Entity("TPArticle.Etagere", b =>
                {
                    b.HasOne("TPArticle.Secteur", null)
                        .WithMany("Etageres")
                        .HasForeignKey("SecteurId");
                });
#pragma warning restore 612, 618
        }
    }
}
